### ISSUE TITLE
How to include multiple library into cql

### ISSUE THREAD

**Issue by nehaghub** [cqframework/cql-translation-service#32]
Hi Team,

I have one concern regarding my cql file. I have divided my cql file into multiple libraries that includes common functions.
I am not able to translate that using cql-translation-service.

Can you tell me the method how to include multiple libraries into my cql file. That will be very helpful.

Thanks,
Neha Goel

**Comment by nehaghub** [comment]
Hi @cmoesel ,
Thanks for your quick reply. Actually my question is different. Kindly check my sample CQL below

library PatientDeviceObservations version '1.0.0' using FHIR version '4.0.1' 

**include FHIRHelpers version '4.0.1'  called FHIRHelpers
include QA_Status version '1.1.0' called Status**

parameter MeasurementPeriod default Interval[DateTime(1952, 1, 1, 0, 0, 0, 0), DateTime(2021, 1, 1, 0, 0, 0, 0) ] 
context Patient  
define InDemographic: 
    AgeInYearsAt(start of MeasurementPeriod) >= 2 and Patient.gender.value = 'male'

Please check if only one library with the name FHIRHelpers is there then it is converting it into ELM.
But, when i am providing my custom library also with the name QA_Status it is throwing below error

**"message": "Could not load source for library NCQA_Status, version 1.1.0.",**

So, I want to know where to give my custom library path to include it.

Thanks,
Neha

**Comment by nehaghub** [comment]
Hi @cmoesel, 
I am new to this.. I will try to implement what you are showing but i have doubt about FHIRHelpers.
If this is the case of multipart form data then why we are not including anything for FHIRHelpers.
Can you check below link 

https://github.com/cqframework/clinical_quality_language/issues/258

In this link they are suggesting us to write our own class for providing library path like this.

public MyLibrarySourceProvider implements LibrarySourceProvider {
     String getLibrarySource(VersionedIdentifier){
     
     }
}

But, I don't know java much so, I am getting confused here.

Thanks,
Neha

**Comment by cmoesel** [comment]
@nehaghub - You do not need to include FHIRHelpers because FHIRHelpers is considered a part of the CQL Translator build chain.  The FHIRHelpers libraries are in the same codebase as the CQL to ELM Translator -- so it just includes them automatically.  In other words, the CQL to ELM Translator already knows all about FHIRHelpers, so it doesn't need you to provide it.

When you have your own custom library, however, the translator doesn't know anything about it.  There is no way for the translator to know anything about it unless you give it to the translator.  The way you do that when using the CQL Translation Service is to put it in a multi-part message.

The answer you found in https://github.com/cqframework/clinical_quality_language/issues/258 is trying to do something a little bit different.  First, it is for people who are running the CQL to ELM Translator Java code themselves (_not_ for people using the CQL Translation Service).  Second, it is for people who want to provide their own custom way of finding libraries (for example, if they keep all of their libraries in a database and want the translator to be able to search the database for them).  So it is a different use case.  I also see that it is a few years old -- and I think that team has made changes to how that all works since then; so that solution might not be right anymore anyway.

**Comment by nehaghub** [comment]
Hi @cmoesel ,

Thank you So much for clarifying this. I will try to do using multipart form data and if any further help required I will ping you if you can help me.

Thanks,
Neha

**Comment by nehaghub** [comment]
Hi @cmoesel ,

Can you please help. I am getting error. I am using this as request
curl --request POST \
  --url http://localhost:8080/cql/translator \
  --header 'Accept: multipart/form-data' \
  --header 'Content-Disposition: form-data' \
  --header 'Content-Type: multipart/form-data' \
  --form 'MAIN=library PatientDeviceObservations version '\''1.0.0'\'' using FHIR version '\''4.0.1'\'' 

include FHIRHelpers version '\''4.0.1'\''  called FHIRHelpers
include QA_Hospice version '\''1.1.0'\'' called Hospice



parameter MeasurementPeriod default Interval[DateTime(1952, 1, 1, 0, 0, 0, 0), DateTime(2021, 1, 1, 0, 0, 0, 0) ] context Patient  define InDemographic:     AgeInYearsAt(start of MeasurementPeriod) >= 2 and Patient.gender.value = '\''male'\''' \
  --form 'HELPER=library NCQA_Hospice version '\''1.1.0'\'' 

using FHIR version '\''4.0.1'\''

include FHIRHelpers version '\''4.0.1'\'' called FHIRHelpers

context Patient'


<img width="753" alt="image" src="https://user-images.githubusercontent.com/13031912/196149091-b6be9d86-3a0e-45d7-aeaf-c6f9ebbe8cbe.png">



Thanks,
Neha

**Comment by cmoesel** [comment]
Hi @nehaghub.  I think you're close! It seems that Insomnia doesn't support the preview for this.  I have the same problem when I try.  But if you change "Preview" to "Source", you'll see the response!

**Comment by nehaghub** [comment]
Hi @cmoesel,

Thank you so much for your support. There was so confusion in my mind. Now, I am able to see the result.

Thanks,
Neha Goel
